In [1]:
import cv2 
import numpy

In [2]:
im_g=cv2.imread("smallgray.png",0)
# o means grayscale 1 means bgr
im_g
#each number is for 

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [4]:
im_g=cv2.imread("smallgray.png",1)
im_g
#transpose and superpostition of 3 layers



array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [7]:
#create new image name, pass 
cv2.imwrite("newsmallgrsy.png",im_g)


True

In [11]:
#OPERATING ON NUMPY ARRAYS
#indexing
a=cv2.imread("smallgray.png",0)
a

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
a[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [16]:
a[0:2,2:4]
#row, columns

array([[104, 121],
       [255, 255]], dtype=uint8)

In [19]:
#iterating
for i in a:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [21]:
for i in a.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [23]:
for i in a.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [35]:
#stacking images
ims=numpy.hstack((a[:,0:2],a))
ims

array([[187, 158, 187, 158, 104, 121, 143],
       [198, 125, 198, 125, 255, 255, 147],
       [209, 134, 209, 134, 255,  97, 182]], dtype=uint8)

In [38]:
imd=numpy.vstack((a,a))
imd

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [43]:
#SPLITTING
lst=numpy.hsplit(a,5)
lst
#(array,parts)
#type list

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]